/**
 * 適応（効能・効果）— ICD10 → 成分 の標準的対応（保険適応リコメンド用）。
 * 標準的・教科書的に安定した適応のみ（例: アムロジピン＝高血圧）。provenance=
 * CURATED_SEED・暫定。PMDA添付文書 効能・効果の構造化取込で全置換される。
 * これは「診断名が付くと適応薬を上位表示＋ハイライト」する推奨の根拠データ。
 */
export const ICD10_LABEL: Record<string, string> = {
  I10: '高血圧症',
  I209: '狭心症',
  I489: '心房細動',
  E119: '2型糖尿病',
  E785: '脂質異常症',
  E039: '甲状腺機能低下症',
  D509: '鉄欠乏性貧血',
  N189: '慢性腎臓病',
  N390: '尿路感染症',
  J459: '気管支喘息',
  J069: '急性上気道炎',
  J039: '急性扁桃炎',
  J189: '肺炎',
  J111: 'インフルエンザ',
  K219: '逆流性食道炎',
  K590: '便秘症',
  M545: '腰痛症',
  M179: '変形性膝関節症',
  F419: '不安障害',
  F329: 'うつ病',
};

/** ICD10 → 適応となる成分コード（COMMON_DRUGS / curated の ingredientCode）。 */
export const INDICATION_BY_ICD10: Record<string, string[]> = {
  I10: [
    'ING_AMLODIPINE', 'ING_NIFEDIPINE', 'ING_BENIDIPINE', 'ING_AZELNIDIPINE',
    'ING_CANDESARTAN', 'ING_TELMISARTAN', 'ING_OLMESARTAN', 'ING_LOSARTAN',
    'ING_ENALAPRIL', 'ING_IMIDAPRIL', 'ING_BISOPROLOL', 'ING_CARVEDILOL',
    'ING_DOXAZOSIN', 'ING_TRICHLORMETHIAZIDE', 'ING_AZOSEMIDE', 'ING_SPIRONOLACTONE',
  ],
  I209: ['ING_AMLODIPINE', 'ING_BISOPROLOL', 'ING_ASPIRIN', 'ING_BENIDIPINE'],
  I489: ['ING_EDOXABAN', 'ING_APIXABAN', 'ING_RIVAROXABAN', 'ING_WARFARIN', 'ING_BISOPROLOL'],
  E119: [
    'ING_METFORMIN', 'ING_SITAGLIPTIN', 'ING_LINAGLIPTIN', 'ING_DAPAGLIFLOZIN',
    'ING_EMPAGLIFLOZIN', 'ING_GLIMEPIRIDE', 'ING_VOGLIBOSE', 'ING_INSULIN_GLARGINE',
  ],
  E785: [
    'ING_ROSUVASTATIN', 'ING_ATORVASTATIN', 'ING_PITAVASTATIN', 'ING_PRAVASTATIN',
    'ING_EZETIMIBE', 'ING_FENOFIBRATE', 'ING_EPA',
  ],
  E039: ['ING_LEVOTHYROXINE'],
  D509: ['ING_FERROUS'],
  N189: ['ING_NAHCO3', 'ING_ALFACALCIDOL', 'ING_FERROUS', 'ING_FUROSEMIDE'],
  N390: ['ING_LEVOFLOXACIN', 'ING_CEFCAPENE', 'ING_SToxazole', 'ING_AMOXICLAV'],
  J459: ['ING_MONTELUKAST', 'ING_BUD_FORM', 'ING_SALBUTAMOL', 'ING_THEOPHYLLINE', 'ING_TIOTROPIUM'],
  J069: ['ING_ACETAMINOPHEN', 'ING_CARBOCISTEINE', 'ING_AMBROXOL', 'ING_DEXTROMETHORPHAN'],
  J039: ['ING_AMOXICILLIN', 'ING_AMOXICLAV', 'ING_CEFCAPENE', 'ING_CLARITHROMYCIN', 'ING_AZITHROMYCIN', 'ING_ACETAMINOPHEN'],
  J189: ['ING_AMOXICLAV', 'ING_LEVOFLOXACIN', 'ING_CEFTRIAXONE', 'ING_AZITHROMYCIN'],
  J111: ['ING_OSELTAMIVIR', 'ING_ACETAMINOPHEN'],
  K219: ['ING_LANSOPRAZOLE', 'ING_RABEPRAZOLE', 'ING_ESOMEPRAZOLE', 'ING_VONOPRAZAN', 'ING_FAMOTIDINE', 'ING_REBAMIPIDE'],
  K590: ['ING_MGOXIDE', 'ING_SENNOSIDE'],
  M545: ['ING_LOXOPROFEN', 'ING_CELECOXIB', 'ING_DICLOFENAC', 'ING_EPERISONE', 'ING_ACETAMINOPHEN', 'ING_LOXOPROFEN_TAPE'],
  M179: ['ING_LOXOPROFEN', 'ING_CELECOXIB', 'ING_ACETAMINOPHEN', 'ING_DICLOFENAC_GEL', 'ING_LOXOPROFEN_TAPE'],
  F419: ['ING_ESCITALOPRAM', 'ING_SERTRALINE', 'ING_LORAZEPAM', 'ING_ETIZOLAM'],
  F329: ['ING_SERTRALINE', 'ING_ESCITALOPRAM', 'ING_DULOXETINE', 'ING_MIRTAZAPINE'],
};
